### PR TITLE
Updated online help URL

### PR DESCRIPTION
**Pull request by nicolehli**
Issue #23

### CODE REVIEW

**Comment by SunyataZero** [comment]
Thank you!

**Comment by JedMeister** [comment]
@nicolehli - FWIW, instead of writing

> Issue #23

if you had written something like:

> closes #23

or 

> fixes #23 

instead, then GitHub would have auto-closed issue#23 when @SunyataZero merged your pull request! It's not that big a deal to browse to the issue and close it, but is a pretty cool little trick that saves having to remember to do that! I'm sure @SunyataZero and other devs who you contribute too will appreciate it! :smile:

**Comment by nicolehli** [comment]
Really! Def doing that from now on

**Comment by andy5995** [comment]
I saw this was fixed. Thanks @nicolehli :)

@SunyataZero there may need to be a change in how this URL is called. When I click "online help", after a few seconds I get a Firefox dialog box that says

>Firefox is already running, but is not responding. To open a new window, you must first close the existing Firefox process, or restart your system.

**Comment by SunyataZero** [comment]
@andy5995 @nicolehli I tested it on Chrome and it works there, could this be an issue with Firefox? Have you been able to replicate this issue? Kind Regards, Tord

**Comment by JedMeister** [comment]
@andy5995 - I suspect that is something going on with your system rather than something specific wrong here. In my experience, that message occurs when firefox has crashed (or been closed) but there are still background processes running. 

I suggest that you make sure firefox isn't running first. Assuming you're on Linux:
````
sudo ps aux | grep firefox
````
If it's not running, you should get a single process (the grep/search line for firefox). If it's running, you'll get at least 2, possibly more lines. You can kill each of the pids individually, but it's probably easier to just use `killall`:
````
sudo killall fiefox
````

**Comment by andy5995** [comment]
Thanks for the feedback and tips.

The situation is this:
1. I normally have Firefox open, and several pages open in tabs
2. With FF open
  * the link opens in a new tab in FF, adding to my existing open tabs when clicking on a link in:
    * liferea (my rss reader)
    * Thunderbird
    * HexChat

  * when I click "online help" in MatC, I get the message
>Firefox is already running, but is not responding. To open a new window, you must first close the existing Firefox process, or restart your system.

I just tested with Steam but have the same problem as MatC

**Comment by nicolehli** [comment]
Hi @andy5995 @SunyataZero , I tried clicking Online help on a freshly installed 56.0 (64-bit) up to date Firefox browser (I didn't have firefox on my new Windows computer, fresh install) and the issue does not happen.

**Pull request merged**
