### PR TITLE
Fixed blank rest actions issue

### PR DESCRIPTION
**Pull request by toonarmycaptain**
Modified rest_actions_cw.py such that when user attempts to add, if nothing is entered, will return scope rather than adding the blank entry.

### CODE REVIEW

**Comment by SunyataZero** [comment]
Thank you for contributing❣ Kind Regards, Tord

**Comment by andy5995** [comment]
Cool!

If you need any help syncing your fork, @toonarmycaptain please let us know. You should definitely [sync](https://github.com/SunyataZero/mindfulness-at-the-computer/blob/master/CONTRIBUTING.md#syncing) before starting another patch; it will make things a lot easier for you.

Because you made your contribution from your master branch, you will have to use git reset before you sync, otherwise you will probably get merge conflicts or some other obstacles blocking you.

**Comment by toonarmycaptain** [comment]
Oh, so next time I should create a fork? Then do this for each patch/pull?

**Comment by andy5995** [comment]
Well, I see that you have already forked the project. This is the page for your fork: https://github.com/toonarmycaptain/mindfulness-at-the-computer

Basically, the PR procedure outlined on the contributing page is a procedure you'll be able to use on almost any GitHub project you may work on in the future. It's the method most preferred by GitHub project managers.

To prepare for your next path, I would suggest starting at **Pull Requests** -> step 2 (cloning). You can skip the parts about making a patch, then try to **Sync**. Let me know if you get stuck.

**Pull request merged**
