### PR TITLE
added type hints for all the methods within the mc_global.py file

### PR DESCRIPTION
**Pull request by wjiang0**
Added type hints for return values on all the functions within this file that did not have them already set. Might want to check about how you want type hints for return values for QFont classes, but otherwise was pretty straightforward.

### CODE REVIEW

**Comment by SunyataZero** [comment]
@wjiang0 Thank you for working on this,
the Travis build gives
`NameError: name 'QFont' is not defined`,
i think this is because you need to add `QtGui.` before, can you add this?
Kind Regards, Tord

**Comment by SunyataZero** [comment]
@wjiang0 I think a pull request has to remain open for it to be merged, PRs are closed only when we don't want to use them. If you like you could open a new PR though (to make the change discussed above), and then close this one, or we can work within this PR directly. Kind Regards, Tord

**Comment by SunyataZero** [comment]
@wjiang0 It looks good now, thank you! I'm merging now. /Tord

**Comment by wjiang0** [comment]
@SunyataZero Sorry about that, I was just in the process of adding that in after seeing the issues with the Travis build. Also sorry about closing the PR, didn't mean to go about doing that, we can continue to work in this PR. The fixes should be in place though.

**Pull request merged**
